export const GLOBAL_CHANGE_TABBAR_ITEM: string = 'GLOBAL_CHANGE_TABBAR_ITEM'
export const GLOBAL_PLAY_SONG: string = 'GLOBAL_PLAY_SONG'
export const GLOBAL_PLAY_PAUSE: string = 'GLOBAL_PLAY_PAUSE'
export const GLOBAL_CHANGE_LYRIC: string = 'GLOBAL_CHANGE_LYRIC'

export const NEWSONG_CHANGE_DATA: string = 'NEWSONG_CHANGE_DATA'
