export const GLOBAL_CHANGE_TABBAR_ITEM: string = 'GLOBAL_CHANGE_TABBAR_ITEM'
export const GLOBAL_PLAY_SONG: string = 'GLOBAL_PLAY_SONG'
export const GLOBAL_PLAY_PAUSE: string = 'GLOBAL_PLAY_PAUSE'
export const GLOBAL_CHANGE_CURNUM: string = 'GLOBAL_CHANGE_CURNUM'
export const GLOBAL_PLAY_BY_INDEX: string = 'GLOBAL_PLAY_BY_INDEX'
export const GLOBAL_SET_CURRENTTIME: string = 'GLOBAL_SET_CURRENTTIME'
export const GLOBAL_CHANGE_RANKINFO_DATA: string = 'GLOBAL_CHANGE_RANKINFO_DATA'
export const GLOBAL_CHANGE_PLISTINFO_DATA: string =
  'GLOBAL_CHANGE_PLISTINFO_DATA'

export const NEWSONG_CHANGE_DATA: string = 'NEWSONG_CHANGE_DATA'

export const RANK_CHANGE_DATA: string = 'RANK_CHANGE_DATA'

export const PLIST_CHANGE_DATA: string = 'PLIST_CHANGE_DATA'

export const SINGER_CHANGE_CLASS_DATA: string = 'SINGER_CHANGE_CLASS_DATA'
export const SINGER_CHANGE_LIST_DATA: string = 'SINGER_CHANGE_LIST_DATA'
export const SINGER_CHANGE_INFO_DATA: string = 'SINGER_CHANGE_INFO_DATA'

export const SEARCH_CHANGE_HOT_DATA: string = 'SEARCH_CHANGE_HOT_DATA'
export const SEARCH_CHANGE_RESULT_DATA: string = 'SEARCH_CHANGE_RESULT_DATA'

export const AREA_CHANGE_DATA: string = 'AREA_CHANGE_DATA'
